#!/usr/bin/env bash
#bash script to display "To Infinity and Beyond " indefinirtely, sleep 2 between iteration
#I am invicible!! when receiving SIGTERM signal
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM
done
