#!/usr/bin/env bash
# write a bash script that displays numbers from 1 to 100
# display fizzbuzz for multiples of 3 and 5
#display fizz for multiples of 3
#display buzz for multiples of 5
#otherwise number in list format
for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
