#!/usr/bin/env bash
#Bash script displaying Best School ten times but 9th display Best School and then Hi on a new line

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
